"""Daemon reflection scheduler with cooldowns and quiet hours."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, date, datetime
from pathlib import Path
from typing import Literal, cast

from langchain_core.messages import HumanMessage, SystemMessage
from pydantic import BaseModel, ConfigDict, Field, ValidationError, field_validator

from nuself.agent.errors import AgentError
from nuself.agent.structured import StructuredAgent, default_structured_agent
from nuself.config import runtime_paths
from nuself.config import ConfigSystem, ReflectionSettings
from nuself.clock import utc_now_iso
from nuself.domain.proactive import IdeaCandidate, IdeaCandidateType, RelevanceScore
from nuself.notification import NotificationOutbox, OutboxEntry
from nuself.notification.deep_link import DeepLink
from nuself.reflection.audit import (
    report_reflection_failure,
    write_reflection_audit,
)
from nuself.reflection.organizer import ReflectionOrganizer
from nuself.reflection.repository import ReflectionEntry, ReflectionRepository
from nuself.persona import PersonaCompetitionResult, SharedPersonaDiscussionService
from nuself.persona.audit import write_persona_audit
from nuself.runtime.diagnostics import diagnostic_exception_message
from nuself.storage import write_json_atomic

REFLECTION_SCHEDULE_STATE_VERSION = 1


class ReflectionScheduleStateError(ValueError):
    """Raised when persisted reflection schedule state is not trustworthy."""


class ReflectionScheduleState(BaseModel):
    """Strict persisted cooldown and daily-cap state."""

    model_config = ConfigDict(strict=True, extra="forbid")

    schema_version: Literal[1]
    timestamp: datetime
    daily_count: int = Field(ge=0)
    daily_date: date
    title: str | None = None
    body: str | None = None

    @field_validator("timestamp")
    @classmethod
    def _timestamp_must_be_aware(cls, value: datetime) -> datetime:
        if value.tzinfo is None or value.utcoffset() is None:
            raise ValueError("timestamp must be timezone-aware")
        return value

    def to_record(self) -> dict[str, object]:
        return cast(dict[str, object], self.model_dump(mode="json", exclude_none=True))


def _read_reflection_schedule_state(path: Path) -> ReflectionScheduleState | None:
    if not path.exists():
        return None
    try:
        return ReflectionScheduleState.model_validate_json(
            path.read_text(encoding="utf-8")
        )
    except OSError:
        raise ReflectionScheduleStateError(
            "reflection schedule state could not be read"
        ) from None
    except ValidationError:
        raise ReflectionScheduleStateError(
            "reflection schedule state is malformed or unsupported"
        ) from None


class RelevanceScoreOutput(BaseModel):
    """Structured relevance evaluation returned by the LLM."""

    model_config = ConfigDict(strict=True, extra="forbid")

    passes: bool = Field(description="Whether the candidate passes the relevance gate.")
    novelty: float = Field(ge=0, le=1, description="Novelty score from 0.0 to 1.0.")
    confidence: float = Field(ge=0, le=1, description="Confidence score from 0.0 to 1.0.")
    urgency: float = Field(ge=0, le=1, description="Urgency score from 0.0 to 1.0.")
    interruption_cost: float = Field(
        ge=0,
        le=1,
        description="Interruption cost from 0.0 to 1.0.",
    )
    composite: float = Field(ge=0, le=1, description="Composite relevance score from 0.0 to 1.0.")
    reason: str = Field(min_length=1, description="Reason for the assessment.")


class CandidateItemOutput(BaseModel):
    """One candidate idea generated by the LLM."""

    model_config = ConfigDict(strict=True, extra="forbid")

    title: str = Field(min_length=1, max_length=80, description="Candidate title.")
    body: str = Field(min_length=1, description="Candidate body text.")
    candidate_type: IdeaCandidateType = Field(
        description="Type of candidate.",
    )
    confidence: float = Field(ge=0, le=1, description="Confidence score from 0.0 to 1.0.")
    novelty: float = Field(ge=0, le=1, description="Novelty score from 0.0 to 1.0.")
    urgency: float = Field(ge=0, le=1, description="Urgency score from 0.0 to 1.0.")
    interruption_cost: float = Field(
        ge=0,
        le=1,
        description="Interruption cost from 0.0 to 1.0.",
    )


class CandidateListOutput(BaseModel):
    """Structured list of candidate ideas returned by the LLM."""

    model_config = ConfigDict(strict=True, extra="forbid")

    candidates: list[CandidateItemOutput] = Field(
        max_length=3,
        description="Generated candidate ideas.",
    )


class ReflectionScheduler:
    """Decides when the daemon should run a self-reflection cycle."""

    def __init__(self, project_root: Path | None = None, config: ReflectionSettings | None = None) -> None:
        paths = runtime_paths(project_root)
        self._project_root = paths.project_root

        if config is not None:
            self._config = config
        else:
            system_config = ConfigSystem.load(project_root=project_root)
            self._config = system_config.reflection

        self._last_reflection_path = paths.runtime_dir / "last_reflection.json"
        self._reflection_repo = ReflectionRepository(project_root)
        self._outbox = NotificationOutbox(project_root)
    def should_reflect(self, now: datetime | None = None) -> bool:
        """Return whether deterministic scheduling gates allow a reflection cycle."""
        if now is None:
            now = datetime.now(UTC)
        return self._schedule_block_reason(now) is None

    def reflect(self, now: datetime | None = None) -> bool:
        """Run one reflection cycle if conditions pass."""
        
        if now is None:
            now = datetime.now(UTC)
        
        block_reason = self._schedule_block_reason(now)
        if block_reason is not None:
            write_reflection_audit(
                "schedule_blocked",
                "reflection cycle skipped by schedule limits",
                project_root=self._project_root,
                metadata={"reason": block_reason},
            )
            return False
        
        write_reflection_audit(
            "cycle_started",
            "reflection cycle triggered",
            project_root=self._project_root,
        )

        self._organize_pending_reflections()

        candidates = IdeaCandidateGenerator(self._project_root, config=self._config).generate()
        if not candidates:
            return False
        
        gate = LLMRelevanceGate(self._project_root, config=self._config)
        best = candidates[0]
        score = gate.score(best)
        if not score.passes:
            write_reflection_audit(
                "cycle_filtered",
                f"best candidate filtered by relevance gate: {best.title}",
                project_root=self._project_root,
                metadata={"reason": "filtered_by_gate", "score": float(score.composite)}
            )
            return False
        
        # High-value candidates go through competitive persona discussion
        title = best.title
        body = best.body
        discussion_approved: bool | None = None
        discussion_trace: tuple[str, ...] = ()
        if score.composite >= self._config.gate.persona_discussion_threshold:
            result = SharedPersonaDiscussionService(
                project_root=self._project_root,
                config=self._config,
            ).discuss(best)
            self._write_discussion_log(best, score, result, now)
            discussion_approved = result.approved
            discussion_trace = result.discussion_trace
            if not result.approved:
                write_reflection_audit(
                    "cycle_discussion_rejected",
                    f"persona discussion rejected candidate: {best.title}",
                    project_root=self._project_root,
                    metadata={"reason": "discussion_rejected"}
                )
                return False
            title = result.revised_title
            body = result.revised_body
        
        entry = self._candidate_to_reflection_entry(
            best, now, score, title=title, body=body,
            discussion_approved=discussion_approved,
            discussion_trace=discussion_trace,
        )
        self._reflection_repo.add(entry)
        try:
            from nuself.trace.service import TraceRecorder

            decision_points: list[str] = [
                f"Relevance gate passed: composite={score.composite:.2f} threshold={self._config.gate.relevance_threshold}",
                f"Novelty={score.novelty:.2f} confidence={score.confidence:.2f} urgency={score.urgency:.2f}",
            ]
            if discussion_approved is not None:
                decision_points.append(
                    f"Persona discussion threshold met (composite >= {self._config.gate.persona_discussion_threshold})"
                )
                decision_points.append(
                    f"Persona discussion {'approved' if discussion_approved else 'rejected'}"
                )
            else:
                decision_points.append(
                    f"Below persona discussion threshold ({self._config.gate.persona_discussion_threshold}), no discussion triggered"
                )

            TraceRecorder(project_root=self._project_root).record_reflection_created(
                reflection_id=entry.id,
                title=entry.title,
                body=entry.body,
                candidate_type=entry.candidate_type,
                composite_score=entry.composite_score,
                discussion_approved=entry.discussion_approved,
                thread_id="reflections",
                decision_points=decision_points,
            )
        except Exception as exc:
            report_reflection_failure(
                exc,
                event="trace_recording_failed",
                message="Failed to record trace for persisted reflection",
                project_root=self._project_root,
                metadata={"reflection_id": entry.id},
            )
        self._organize_pending_reflections()
        self._write_last_reflection(now, title=title, body=body)

        if self._config.auto_notify:
            intent = self._candidate_to_notify_entry(entry)
            self._outbox.add(intent)

        write_reflection_audit(
            "cycle_completed",
            f"reflection cycle published: {title}",
            project_root=self._project_root,
            metadata={"reason": "published", "score": float(score.composite), "idea_type": best.candidate_type}
        )
        return True

    def _organize_pending_reflections(self) -> None:

        try:
            ReflectionOrganizer(self._project_root, repository=self._reflection_repo).organize_pending()
        except Exception as exc:
            report_reflection_failure(
                exc,
                event="organizer_failed",
                message="Reflection organizer failed",
                project_root=self._project_root,
                metadata=None,
            )

    def _in_quiet_hours(self, now: datetime) -> bool:
        current_hour = now.astimezone().hour
        start = self._config.scheduler.quiet_start_hour
        end = self._config.scheduler.quiet_end_hour
        if start == end:
            return False
        if start < end:
            return start <= current_hour < end
        # Wraps around midnight, e.g. 22:00–07:00
        return current_hour >= start or current_hour < end

    def _schedule_block_reason(self, now: datetime) -> str | None:
        if self._in_quiet_hours(now):
            return "quiet_hours"
        try:
            state = _read_reflection_schedule_state(
                self._last_reflection_path
            )
        except ReflectionScheduleStateError as exc:
            self._report_schedule_state_corrupt(exc)
            return "state_corrupt"
        if not self._daily_cap_not_reached(now, state):
            return "daily_cap"
        if self._in_cooldown(now, state):
            return "cooldown"
        if self._interval_not_elapsed(now, state):
            return "interval"
        return None

    def _in_cooldown(
        self,
        now: datetime,
        state: ReflectionScheduleState | None,
    ) -> bool:
        if state is None:
            return False
        elapsed = (now - state.timestamp).total_seconds()
        return elapsed < self._config.scheduler.cooldown_seconds

    def _interval_not_elapsed(
        self,
        now: datetime,
        state: ReflectionScheduleState | None,
    ) -> bool:
        if state is None:
            return False
        jittered = self._jittered_interval()
        elapsed = (now - state.timestamp).total_seconds()
        return elapsed < jittered

    def _jittered_interval(self) -> int:
        import random

        base = self._config.scheduler.interval_seconds
        jitter = base * self._config.scheduler.jitter_percent // 100
        if jitter == 0:
            return base
        return base + random.randint(-jitter, jitter)

    def _daily_cap_not_reached(
        self,
        now: datetime,
        state: ReflectionScheduleState | None,
    ) -> bool:
        count = self._reflection_count_today(now, state)
        return count < self._config.scheduler.daily_cap

    def _reflection_count_today(
        self,
        now: datetime,
        state: ReflectionScheduleState | None,
    ) -> int:
        if state is None:
            return 0
        if state.daily_date == now.astimezone().date():
            return state.daily_count
        return 0

    def _read_last_reflection(self) -> datetime | None:
        state = _read_reflection_schedule_state(
            self._last_reflection_path
        )
        return state.timestamp if state is not None else None

    def _write_last_reflection(self, now: datetime, title: str | None = None, body: str | None = None) -> None:
        current = _read_reflection_schedule_state(
            self._last_reflection_path
        )
        count = self._reflection_count_today(now, current) + 1
        state = ReflectionScheduleState(
            schema_version=REFLECTION_SCHEDULE_STATE_VERSION,
            timestamp=now,
            daily_count=count,
            daily_date=now.astimezone().date(),
            title=title,
            body=body,
        )
        write_json_atomic(self._last_reflection_path, state.to_record())

    def _report_schedule_state_corrupt(
        self,
        exc: ReflectionScheduleStateError,
    ) -> None:
        report_reflection_failure(
            exc,
            event="schedule_state_corrupt",
            message="Reflection schedule state is invalid; scheduling is blocked",
            project_root=self._project_root,
            metadata={"record": self._last_reflection_path.name},
        )

    def _candidate_to_reflection_entry(
        self,
        candidate: IdeaCandidate,
        now: datetime,
        score: RelevanceScore,
        title: str | None = None,
        body: str | None = None,
        discussion_approved: bool | None = None,
        discussion_trace: tuple[str, ...] = (),
    ) -> ReflectionEntry:

        thread_id = candidate.suggested_thread_id or "reflections"
        deep_link = DeepLink(action="open_thread", thread_id=thread_id).to_url()
        return ReflectionEntry(
            id=f"reflection-{candidate.id}",
            title=title if title is not None else candidate.title,
            body=body if body is not None else candidate.body,
            candidate_type=candidate.candidate_type,
            confidence=candidate.confidence,
            novelty=candidate.novelty,
            urgency=candidate.urgency,
            interruption_cost=candidate.interruption_cost,
            composite_score=score.composite,
            status="pending",
            discussion_approved=discussion_approved,
            discussion_trace=discussion_trace,
            deep_link=deep_link,
            created_at=now.isoformat(),
            reviewed_at=None,
        )

    def _candidate_to_notify_entry(self, entry: ReflectionEntry) -> OutboxEntry:
        return OutboxEntry(
            id=f"notify-{entry.id}",
            title=f"New reflection: {entry.title}",
            body=f"A new reflection idea is available. View it with: nuself reflection show {entry.id}",
            status="pending",
            idempotency_key=f"notify-{entry.id}",
            deep_link=entry.deep_link,
        )

    def _write_discussion_log(
        self,
        candidate: IdeaCandidate,
        score: RelevanceScore,
        result: object,
        now: datetime,
    ) -> None:

        if not isinstance(result, PersonaCompetitionResult):
            return
        del score, now
        write_persona_audit(
            "persona_discussion",
            project_root=self._project_root,
            metadata={
                "candidate_id": candidate.id,
                "approved": result.approved,
                "winner_count": len(result.winner_persona_ids),
                "emergent_count": len(result.emergent_persona_ids),
                "blocking_veto_count": len(result.blocking_vetos),
                "score_count": len(result.scores),
                "discussion_steps": len(result.discussion_trace),
            },
        )


class LLMRelevanceGate:
    """LLM-driven relevance gate for proactive candidates."""

    def __init__(
        self,
        project_root: Path | None = None,
        config: ReflectionSettings | None = None,
        agent: StructuredAgent[RelevanceScoreOutput] | None = None,
    ) -> None:
        paths = runtime_paths(project_root)
        self._project_root = paths.project_root
        self._last_reflection_path = paths.runtime_dir / "last_reflection.json"

        if config is not None:
            self._config = config
        else:
            system_config = ConfigSystem.load(project_root=project_root)
            self._config = system_config.reflection

        self._agent = agent or default_structured_agent(
            RelevanceScoreOutput,
            project_root=self._project_root,
            component="reflection",
        )
        self._reflection_repo = ReflectionRepository(self._project_root)

    def score(self, candidate: IdeaCandidate) -> RelevanceScore:
        cooldown_ok = self._cooldown_ok()
        try:
            output = self._invoke_agent(candidate, cooldown_ok)
        except AgentError as exc:
            return self._observed_fallback(candidate, cooldown_ok, exc)
        try:
            return self._score_from_output(output, cooldown_ok)
        except ValueError as exc:
            return self._observed_fallback(candidate, cooldown_ok, exc)

    def passes(self, candidate: IdeaCandidate) -> bool:
        return self.score(candidate).passes

    def _invoke_agent(
        self,
        candidate: IdeaCandidate,
        cooldown_ok: bool,
    ) -> RelevanceScoreOutput:
        recent = self._reflection_repo.list()[:3]
        messages = self._build_prompt(candidate, recent, cooldown_ok)
        return self._agent.invoke(messages)

    def _observed_fallback(
        self,
        candidate: IdeaCandidate,
        cooldown_ok: bool,
        error: ValueError | AgentError,
    ) -> RelevanceScore:
        detail = diagnostic_exception_message(error)
        write_reflection_audit(
            "relevance_gate_fallback",
            f"Relevance agent failed, using fallback: {detail}",
            project_root=self._project_root,
        )
        return self._fallback_score(candidate, cooldown_ok)

    def _build_prompt(
        self,
        candidate: IdeaCandidate,
        recent: list[ReflectionEntry],
        cooldown_ok: bool,
    ) -> list[SystemMessage | HumanMessage]:

        system = (
            "You are the Relevance Gate for NuSelf, a private AI mirror. Your job is to judge "
            "whether a newly generated reflection idea is worth surfacing to the user right now.\n\n"
            "Judge these dimensions (0.0–1.0):\n"
            "- novelty: Is this genuinely new relative to recent reflections? Consider semantic meaning, not just string similarity.\n"
            "- confidence: How well-supported is this idea by the user's memory and conversations?\n"
            "- urgency: How time-sensitive is this? Should the user see it soon?\n"
            "- interruption_cost: How disruptive would it be to interrupt the user with this now?\n"
            "- composite: Your overall assessment of the idea's value.\n"
            "- passes: Should this idea be allowed through the gate? (true/false)\n"
            "- reason: A brief sentence explaining your judgment."
        )

        lines = [
            "Candidate:",
            f"- Title: {candidate.title}",
            f"- Body: {candidate.body}",
            f"- Type: {candidate.candidate_type}",
            f"- Original scores: confidence={candidate.confidence:.2f}, novelty={candidate.novelty:.2f}, urgency={candidate.urgency:.2f}, interruption={candidate.interruption_cost:.2f}",
            "",
        ]

        if recent:
            lines.append("Recent reflections:")
            for i, entry in enumerate(recent, start=1):
                lines.append(f"{i}. [{entry.candidate_type}] {entry.title}: {entry.body[:200]}")
        else:
            lines.append("No recent reflections.")

        lines.extend([
            "",
            f"Cooldown active: {'no' if cooldown_ok else 'yes'}",
            f"Time: {datetime.now(UTC).isoformat()}",
        ])

        return [
            SystemMessage(content=system),
            HumanMessage(content="\n".join(lines)),
        ]

    def _score_from_output(
        self,
        output: RelevanceScoreOutput,
        cooldown_ok: bool,
    ) -> RelevanceScore:
        return RelevanceScore(
            passes=output.passes,
            novelty=output.novelty,
            confidence=output.confidence,
            urgency=output.urgency,
            interruption_cost=output.interruption_cost,
            cooldown_ok=cooldown_ok,
            composite=output.composite,
            reasons=(output.reason,),
        )

    def _fallback_score(self, candidate: IdeaCandidate, cooldown_ok: bool) -> RelevanceScore:
        return RelevanceScore(
            passes=False,
            novelty=candidate.novelty,
            confidence=candidate.confidence,
            urgency=candidate.urgency,
            interruption_cost=candidate.interruption_cost,
            cooldown_ok=cooldown_ok,
            composite=0.0,
            reasons=("llm_fallback",),
        )

    def _cooldown_ok(self) -> bool:
        try:
            state = _read_reflection_schedule_state(
                self._last_reflection_path
            )
        except ReflectionScheduleStateError as exc:
            report_reflection_failure(
                exc,
                event="schedule_state_corrupt",
                message=(
                    "Reflection schedule state is invalid; "
                    "cooldown remains active"
                ),
                project_root=self._project_root,
                metadata={"record": self._last_reflection_path.name},
            )
            return False
        if state is None:
            return True
        elapsed = (datetime.now(UTC) - state.timestamp).total_seconds()
        return elapsed >= self._config.scheduler.cooldown_seconds


class IdeaCandidateGenerator:
    """Proactively generate new ideas from memory, sources, and conversations.

    The daemon calls this periodically. It reads whatever data exists and uses
    the LLM to produce genuinely new ideas — connections, contradictions,
    questions, and actions that the user hasn't explicitly asked about.
    """

    def __init__(
        self,
        project_root: Path | None = None,
        *,
        agent: StructuredAgent[CandidateListOutput] | None = None,
        config: ReflectionSettings | None = None,
    ) -> None:
        paths = runtime_paths(project_root)
        self._project_root = paths.project_root
        self._agent = agent or default_structured_agent(
            CandidateListOutput,
            project_root=self._project_root,
            component="reflection",
        )

        if config is not None:
            self._config_obj = config
        else:
            system_config = ConfigSystem.load(project_root=self._project_root)
            self._config_obj = system_config.reflection

        # Load language preference for user-facing output
        system_config = ConfigSystem.load(project_root=self._project_root)
        self._language_preference = system_config.chat.language_preference

    def generate(self, max_candidates: int = 3) -> list[IdeaCandidate]:
        
        context = self._collect_context()
        if context.is_empty():
            write_reflection_audit(
                "candidate_generation_skipped",
                "no context available for idea generation",
                project_root=self._project_root,
                metadata={"reason": "empty_context"}
            )
            return []
        try:
            output = self._invoke_agent(context)
        except AgentError as exc:
            return self._observed_generation_failure(exc)
        try:
            candidates = self._candidates_from_output(output, max_candidates)
        except ValueError as exc:
            return self._observed_generation_failure(exc)
        if not candidates:
            write_reflection_audit(
                "cycle_no_candidates",
                "reflection cycle generated no candidates",
                project_root=self._project_root,
                metadata={"reason": "no_candidates"}
            )
        return candidates

    def _collect_context(self) -> _ThinkingContext:
        threads = self._recent_thread_context()
        memories = self._recent_memory_context()
        profile = self._profile_context()
        sources = self._new_source_context()
        return _ThinkingContext(
            threads=threads,
            memories=memories,
            profile=profile,
            sources=sources,
        )

    def _invoke_agent(
        self,
        context: _ThinkingContext,
    ) -> CandidateListOutput:

        system_prompt = (
            "You are an independent thinker with access to someone's private memory, "
            "conversation history, reading notes, and personal profile.\n\n"
            "Your job: generate NEW ideas that the person hasn't explicitly asked about. "
            "Look for:\n"
            "- Contradictions between different memories or stated beliefs\n"
            "- Connections between seemingly unrelated topics\n"
            "- Unexplored questions suggested by the data\n"
            "- Actionable insights or recommendations\n"
            "- Patterns the person might not have noticed\n\n"
            "Do NOT summarize or rephrase existing content. "
            "Do NOT produce generic observations. "
            "Each idea must be genuinely novel — something the person would "
            "not have thought of on their own. Return up to three candidates "
            "through the required structured response."
        )
        if self._language_preference != "en":
            system_prompt += f"\n\nRespond in {self._language_preference}."

        user_message = context.to_prompt()
        messages = [
            SystemMessage(content=system_prompt),
            HumanMessage(content=user_message),
        ]
        return self._agent.invoke(messages)

    def _observed_generation_failure(
        self,
        error: ValueError | AgentError,
    ) -> list[IdeaCandidate]:
        report_reflection_failure(
            error,
            event="candidate_generation_failed",
            message=f"failed to generate candidates: {type(error).__name__}",
            project_root=self._project_root,
            metadata=None,
        )
        return []

    def _candidates_from_output(
        self,
        output: CandidateListOutput,
        max_candidates: int,
    ) -> list[IdeaCandidate]:
        now = datetime.now(UTC)
        prefix = now.strftime("%Y%m%d-%H%M%S")
        results: list[IdeaCandidate] = []
        for item in output.candidates[:max_candidates]:
            results.append(IdeaCandidate(
                id=f"candidate-{prefix}-{now.microsecond:06d}",
                title=item.title,
                body=item.body,
                candidate_type=item.candidate_type,
                confidence=item.confidence,
                novelty=item.novelty,
                urgency=item.urgency,
                interruption_cost=item.interruption_cost,
                evidence_refs=(),
                suggested_thread_id=None,
                source_summary="llm-generated",
                created_at=utc_now_iso(),
            ))
        return results

    def _recent_thread_context(self, max_threads: int = 5, max_messages: int = 10) -> str:
        from nuself.agent.chat import ThreadStore

        store = ThreadStore(self._project_root)
        lines: list[str] = []
        for thread_id in reversed(store.list()[-max_threads:]):
            state = store.load(thread_id)
            lines.append(f"Thread {thread_id}:")
            for msg in state.messages[-max_messages:]:
                lines.append(f"  {msg.role}: {msg.content[:120]}")
        return "\n".join(lines)

    def _recent_memory_context(self, max_entries: int = 8) -> str:
        from nuself.memory.repository import MemoryEntryRepository

        repo = MemoryEntryRepository(self._project_root)
        lines: list[str] = []
        for entry in repo.list()[-max_entries:]:
            lines.append(f"- [{entry.type}] {entry.title}: {entry.body[:120]}")
        return "\n".join(lines)

    def _profile_context(self, max_items: int = 10) -> str:
        from nuself.profile.repository import ProfileItemRepository

        repo = ProfileItemRepository(self._project_root)
        lines: list[str] = []
        for item in repo.list()[:max_items]:
            tags = f" (tags: {', '.join(item.tags)})" if item.tags else ""
            lines.append(f"- [{item.type}] {item.title}{tags}: {item.body[:120]}")
        return "\n".join(lines)

    def _new_source_context(self, max_sources: int = 5) -> str:
        from nuself.memory.source_repository import SourceRepository

        repo = SourceRepository(self._project_root)
        lines: list[str] = []
        for doc in repo.list_documents()[-max_sources:]:
            lines.append(f"- {doc.title or doc.id}")
        return "\n".join(lines)


@dataclass(frozen=True)
class _ThinkingContext:
    """All available material for proactive idea generation."""

    threads: str
    memories: str
    profile: str
    sources: str

    def is_empty(self) -> bool:
        return not (self.threads or self.memories or self.profile or self.sources)

    def to_prompt(self) -> str:
        sections: list[str] = []
        if self.memories:
            sections.append(f"## Memory entries\n{self.memories}")
        if self.threads:
            sections.append(f"## Recent conversations\n{self.threads}")
        if self.profile:
            sections.append(f"## Personal profile\n{self.profile}")
        if self.sources:
            sections.append(f"## Source documents\n{self.sources}")
        return "\n\n".join(sections)
