"""Daemon reflection scheduler with cooldowns and quiet hours."""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING, cast

from pydantic import BaseModel, Field, ValidationError

from nuself.config import runtime_paths
from nuself.config import ConfigSystem, ReflectionSettings
from nuself.domain.memory import now_iso
from nuself.domain.proactive import IdeaCandidate, IdeaCandidateType, RelevanceScore
from nuself.notification import NotificationOutbox, OutboxEntry
from nuself.reflection.organizer import ReflectionOrganizer
from nuself.reflection.repository import ReflectionEntry, ReflectionRepository
from nuself.llm import default_llm
from nuself.persona_discussion_service import SharedPersonaDiscussionService

if TYPE_CHECKING:
    from nuself.llm import ChatLLM, ChatMessage


@dataclass(frozen=True)
class ReflectionEvent:
    """Event that can trigger an immediate reflection cycle."""

    event_type: str
    payload: dict[str, object]
    created_at: str


class RelevanceScoreOutput(BaseModel):
    """Structured relevance evaluation returned by the LLM."""

    passes: bool = Field(description="Whether the candidate passes the relevance gate.")
    novelty: float = Field(description="Novelty score from 0.0 to 1.0.")
    confidence: float = Field(description="Confidence score from 0.0 to 1.0.")
    urgency: float = Field(description="Urgency score from 0.0 to 1.0.")
    interruption_cost: float = Field(description="Interruption cost from 0.0 to 1.0.")
    composite: float = Field(description="Composite relevance score from 0.0 to 1.0.")
    reason: str = Field(default="llm judgment", description="Reason for the assessment.")


class CandidateItemOutput(BaseModel):
    """One candidate idea generated by the LLM."""

    title: str = Field(description="Candidate title (max 80 chars).")
    body: str = Field(description="Candidate body text.")
    candidate_type: str = Field(default="question", description="Type of candidate.")
    confidence: float = Field(default=0.5, description="Confidence score from 0.0 to 1.0.")
    novelty: float = Field(default=0.5, description="Novelty score from 0.0 to 1.0.")
    urgency: float = Field(default=0.3, description="Urgency score from 0.0 to 1.0.")
    interruption_cost: float = Field(default=0.2, description="Interruption cost from 0.0 to 1.0.")


class CandidateListOutput(BaseModel):
    """Structured list of candidate ideas returned by the LLM."""

    candidates: list[CandidateItemOutput] = Field(description="Generated candidate ideas.")


class ReflectionScheduler:
    """Decides when the daemon should run a self-reflection cycle."""

    def __init__(self, project_root: Path | None = None, config: ReflectionSettings | None = None) -> None:
        paths = runtime_paths(project_root)
        self._project_root = paths.project_root

        if config is not None:
            self._config = config
        else:
            system_config = ConfigSystem.load(project_root=project_root)
            self._config = system_config.reflection

        self._last_reflection_path = paths.runtime_dir / "last_reflection.json"
        self._reflection_repo = ReflectionRepository(project_root)
        self._outbox = NotificationOutbox(project_root)
        self._event_queue: list[ReflectionEvent] = []

    def trigger_event(self, event: ReflectionEvent) -> None:
        """Queue an event-triggered reflection request."""
        self._event_queue.append(event)

    def should_reflect(self, now: datetime | None = None) -> bool:
        """Return whether deterministic scheduling gates allow a reflection cycle."""
        if now is None:
            now = datetime.now(UTC)
        return self._schedule_block_reason(now) is None

    def reflect(self, now: datetime | None = None) -> bool:
        """Run one reflection cycle if conditions pass."""
        from nuself.logs import write_log_event
        
        if now is None:
            now = datetime.now(UTC)
        
        block_reason = self._schedule_block_reason(now)
        if block_reason is not None:
            write_log_event(
                "reflection",
                "schedule_blocked",
                "reflection cycle skipped by schedule limits",
                project_root=self._project_root,
                level="info",
                status="skipped",
                metadata={"reason": block_reason},
            )
            return False
        
        write_log_event(
            "reflection",
            "cycle_started",
            "reflection cycle triggered",
            project_root=self._project_root,
            level="info",
            status="started"
        )

        self._organize_pending_reflections()

        # Consume any queued events before generating candidates
        self._event_queue.clear()
        candidates = IdeaCandidateGenerator(self._project_root, config=self._config).generate()
        if not candidates:
            return False
        
        gate = LLMRelevanceGate(self._project_root, config=self._config)
        best = candidates[0]
        score = gate.score(best)
        if not score.passes:
            write_log_event(
                "reflection",
                "cycle_filtered",
                f"best candidate filtered by relevance gate: {best.title}",
                project_root=self._project_root,
                level="info",
                status="completed",
                metadata={"reason": "filtered_by_gate", "score": float(score.composite)}
            )
            return False
        
        # High-value candidates go through competitive persona discussion
        title = best.title
        body = best.body
        discussion_approved: bool | None = None
        discussion_trace: tuple[str, ...] = ()
        if score.composite >= self._config.gate.persona_discussion_threshold:
            result = SharedPersonaDiscussionService(
                project_root=self._project_root,
                config=self._config,
                llm=default_llm(self._project_root),
            ).discuss(best)
            self._write_discussion_log(best, score, result, now)
            discussion_approved = result.approved
            discussion_trace = result.discussion_trace
            if not result.approved:
                write_log_event(
                    "reflection",
                    "cycle_discussion_rejected",
                    f"persona discussion rejected candidate: {best.title}",
                    project_root=self._project_root,
                    level="info",
                    status="completed",
                    metadata={"reason": "discussion_rejected"}
                )
                return False
            title = result.revised_title
            body = result.revised_body
        
        entry = self._candidate_to_reflection_entry(
            best, now, score, title=title, body=body,
            discussion_approved=discussion_approved,
            discussion_trace=discussion_trace,
        )
        self._reflection_repo.add(entry)
        self._organize_pending_reflections()
        self._write_last_reflection(now, title=title, body=body)

        if self._config.auto_notify:
            intent = self._candidate_to_notify_entry(entry)
            self._outbox.add(intent)

        write_log_event(
            "reflection",
            "cycle_completed",
            f"reflection cycle published: {title}",
            project_root=self._project_root,
            level="info",
            status="completed",
            metadata={"reason": "published", "score": float(score.composite), "idea_type": best.candidate_type}
        )
        return True

    def _organize_pending_reflections(self) -> None:
        from nuself.logs import write_log_event

        try:
            ReflectionOrganizer(self._project_root, repository=self._reflection_repo).organize_pending()
        except Exception as exc:
            write_log_event(
                "reflection",
                "organizer_failed",
                "reflection organizer failed",
                project_root=self._project_root,
                level="error",
                status="failed",
                error=str(exc),
            )

    def _in_quiet_hours(self, now: datetime) -> bool:
        current_hour = now.astimezone().hour
        start = self._config.scheduler.quiet_start_hour
        end = self._config.scheduler.quiet_end_hour
        if start == end:
            return False
        if start < end:
            return start <= current_hour < end
        # Wraps around midnight, e.g. 22:00–07:00
        return current_hour >= start or current_hour < end

    def _schedule_block_reason(self, now: datetime) -> str | None:
        if self._in_quiet_hours(now):
            return "quiet_hours"
        if not self._daily_cap_not_reached(now):
            return "daily_cap"
        if self._in_cooldown(now):
            return "cooldown"
        if self._interval_not_elapsed(now):
            return "interval"
        return None

    def _in_cooldown(self, now: datetime) -> bool:
        last = self._read_last_reflection()
        if last is None:
            return False
        if last.tzinfo is None:
            last = last.replace(tzinfo=UTC)
        elapsed = (now - last).total_seconds()
        return elapsed < self._config.scheduler.cooldown_seconds

    def _interval_not_elapsed(self, now: datetime) -> bool:
        last = self._read_last_reflection()
        if last is None:
            return False
        if last.tzinfo is None:
            last = last.replace(tzinfo=UTC)
        jittered = self._jittered_interval()
        elapsed = (now - last).total_seconds()
        return elapsed < jittered

    def _jittered_interval(self) -> int:
        import random

        base = self._config.scheduler.interval_seconds
        jitter = base * self._config.scheduler.jitter_percent // 100
        if jitter == 0:
            return base
        return base + random.randint(-jitter, jitter)

    def _daily_cap_not_reached(self, now: datetime) -> bool:
        count = self._reflection_count_today(now)
        return count < self._config.scheduler.daily_cap

    def _reflection_count_today(self, now: datetime) -> int:
        if not self._last_reflection_path.exists():
            return 0
        try:
            raw: object = json.loads(self._last_reflection_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            return 0
        if not isinstance(raw, dict):
            return 0
        data = cast(dict[str, object], raw)
        count = data.get("daily_count")
        date = data.get("daily_date")
        if not isinstance(count, int) or not isinstance(date, str):
            return 0
        if date == now.astimezone().date().isoformat():
            return count
        return 0

    def _read_last_reflection(self) -> datetime | None:
        if not self._last_reflection_path.exists():
            return None
        try:
            raw: object = json.loads(self._last_reflection_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            return None
        if not isinstance(raw, dict):
            return None
        data = cast(dict[str, object], raw)
        ts_raw = data.get("timestamp")
        if not isinstance(ts_raw, str):
            return None
        try:
            return datetime.fromisoformat(ts_raw)
        except ValueError:
            return None

    def _write_last_reflection(self, now: datetime, title: str | None = None, body: str | None = None) -> None:
        self._last_reflection_path.parent.mkdir(parents=True, exist_ok=True)
        count = self._reflection_count_today(now) + 1
        payload: dict[str, object] = {
            "timestamp": now.isoformat(),
            "daily_count": count,
            "daily_date": now.astimezone().date().isoformat(),
        }
        if title is not None:
            payload["title"] = title
        if body is not None:
            payload["body"] = body
        self._last_reflection_path.write_text(
            json.dumps(payload, sort_keys=True) + "\n",
            encoding="utf-8",
        )

    def _candidate_to_reflection_entry(
        self,
        candidate: IdeaCandidate,
        now: datetime,
        score: RelevanceScore,
        title: str | None = None,
        body: str | None = None,
        discussion_approved: bool | None = None,
        discussion_trace: tuple[str, ...] = (),
    ) -> ReflectionEntry:
        from nuself.notification.deep_link import DeepLink

        thread_id = candidate.suggested_thread_id or "reflections"
        deep_link = DeepLink(action="open_thread", thread_id=thread_id).to_url()
        return ReflectionEntry(
            id=f"reflection-{candidate.id}",
            title=title if title is not None else candidate.title,
            body=body if body is not None else candidate.body,
            candidate_type=candidate.candidate_type,
            confidence=candidate.confidence,
            novelty=candidate.novelty,
            urgency=candidate.urgency,
            interruption_cost=candidate.interruption_cost,
            composite_score=score.composite,
            status="pending",
            discussion_approved=discussion_approved,
            discussion_trace=discussion_trace,
            deep_link=deep_link,
            created_at=now.isoformat(),
            reviewed_at=None,
        )

    def _candidate_to_notify_entry(self, entry: ReflectionEntry) -> OutboxEntry:
        return OutboxEntry(
            id=f"notify-{entry.id}",
            title=f"New reflection: {entry.title}",
            body=f"A new reflection idea is available. View it with: nuself reflection show {entry.id}",
            status="pending",
            idempotency_key=f"notify-{entry.id}",
            deep_link=entry.deep_link,
        )

    def _write_discussion_log(
        self,
        candidate: IdeaCandidate,
        score: RelevanceScore,
        result: object,
        now: datetime,
    ) -> None:
        from nuself.logs import write_log_event
        from nuself.proactive_persona import PersonaCompetitionResult

        if not isinstance(result, PersonaCompetitionResult):
            return
        metadata: dict[str, object] = {
            "candidate_id": candidate.id,
            "candidate_title": candidate.title,
            "candidate_type": candidate.candidate_type,
            "composite": round(score.composite, 3),
            "approved": result.approved,
            "scores": {k: round(v, 3) for k, v in result.scores.items()},
            "blocking_vetos": list(result.blocking_vetos),
            "winner_persona_ids": list(result.winner_persona_ids),
            "emergent_persona_ids": list(result.emergent_persona_ids),
            "discussion_trace": list(result.discussion_trace),
            "revised_title": result.revised_title,
            "revised_body": result.revised_body,
        }
        status = "approved" if result.approved else "rejected"
        write_log_event(
            "persona",
            "persona_discussion",
            f"{candidate.title} — {result.reason}",
            project_root=self._project_root,
            status=status,
            metadata=metadata,
        )


class LLMRelevanceGate:
    """LLM-driven relevance gate for proactive candidates."""

    def __init__(
        self,
        project_root: Path | None = None,
        config: ReflectionSettings | None = None,
        llm: ChatLLM | None = None,
    ) -> None:
        from nuself.config import runtime_paths
        from nuself.llm import default_llm

        paths = runtime_paths(project_root)
        self._project_root = paths.project_root
        self._last_reflection_path = paths.runtime_dir / "last_reflection.json"

        if config is not None:
            self._config = config
        else:
            system_config = ConfigSystem.load(project_root=project_root)
            self._config = system_config.reflection

        self._llm = llm or default_llm(self._project_root)
        self._reflection_repo = ReflectionRepository(self._project_root)

    def score(self, candidate: IdeaCandidate) -> RelevanceScore:
        cooldown_ok = self._cooldown_ok()
        try:
            return self._score_with_llm(candidate, cooldown_ok)
        except (RuntimeError, ValueError, json.JSONDecodeError, KeyError) as e:
            from nuself.logs import write_log_event

            write_log_event(
                "reflection",
                "relevance_gate_fallback",
                f"LLM relevance gate failed, using fallback: {e}",
                project_root=self._project_root,
                level="warning",
                status="error",
            )
            return self._fallback_score(candidate, cooldown_ok)

    def passes(self, candidate: IdeaCandidate) -> bool:
        return self.score(candidate).passes

    def _score_with_llm(self, candidate: IdeaCandidate, cooldown_ok: bool) -> RelevanceScore:
        recent = self._reflection_repo.list()[:3]
        messages = self._build_prompt(candidate, recent, cooldown_ok)
        raw = self._llm.complete(messages)
        return self._parse_response(raw, candidate, cooldown_ok)

    def _build_prompt(
        self,
        candidate: IdeaCandidate,
        recent: list[ReflectionEntry],
        cooldown_ok: bool,
    ) -> list[ChatMessage]:
        from nuself.llm import ChatMessage

        system = (
            "You are the Relevance Gate for NuSelf, a private AI mirror. Your job is to judge "
            "whether a newly generated reflection idea is worth surfacing to the user right now.\n\n"
            "Judge these dimensions (0.0–1.0):\n"
            "- novelty: Is this genuinely new relative to recent reflections? Consider semantic meaning, not just string similarity.\n"
            "- confidence: How well-supported is this idea by the user's memory and conversations?\n"
            "- urgency: How time-sensitive is this? Should the user see it soon?\n"
            "- interruption_cost: How disruptive would it be to interrupt the user with this now?\n"
            "- composite: Your overall assessment of the idea's value.\n"
            "- passes: Should this idea be allowed through the gate? (true/false)\n"
            "- reason: A brief sentence explaining your judgment.\n\n"
            "Return ONLY a JSON object with fields: novelty, confidence, urgency, interruption_cost, composite, passes, reason. "
            "No markdown fences."
        )

        lines = [
            "Candidate:",
            f"- Title: {candidate.title}",
            f"- Body: {candidate.body}",
            f"- Type: {candidate.candidate_type}",
            f"- Original scores: confidence={candidate.confidence:.2f}, novelty={candidate.novelty:.2f}, urgency={candidate.urgency:.2f}, interruption={candidate.interruption_cost:.2f}",
            "",
        ]

        if recent:
            lines.append("Recent reflections:")
            for i, entry in enumerate(recent, start=1):
                lines.append(f"{i}. [{entry.candidate_type}] {entry.title}: {entry.body[:200]}")
        else:
            lines.append("No recent reflections.")

        lines.extend([
            "",
            f"Cooldown active: {'no' if cooldown_ok else 'yes'}",
            f"Time: {datetime.now(UTC).isoformat()}",
        ])

        return [
            ChatMessage(role="system", content=system),
            ChatMessage(role="user", content="\n".join(lines)),
        ]

    def _parse_response(self, raw: str, candidate: IdeaCandidate, cooldown_ok: bool) -> RelevanceScore:
        stripped = raw.strip()
        if stripped.startswith("```"):
            lines = [line for line in stripped.splitlines() if not line.strip().startswith("```")]
            stripped = "\n".join(lines).strip()

        try:
            output = RelevanceScoreOutput.model_validate_json(stripped)
            return RelevanceScore(
                passes=output.passes,
                novelty=max(0.0, min(1.0, output.novelty)),
                confidence=max(0.0, min(1.0, output.confidence)),
                urgency=max(0.0, min(1.0, output.urgency)),
                interruption_cost=max(0.0, min(1.0, output.interruption_cost)),
                cooldown_ok=cooldown_ok,
                composite=max(0.0, min(1.0, output.composite)),
                reasons=(output.reason,),
            )
        except (ValidationError, json.JSONDecodeError):
            pass

        parsed: object = json.loads(stripped)
        if not isinstance(parsed, dict):
            raise ValueError("LLM response is not a JSON object")
        data = cast(dict[str, object], parsed)

        def _get_float(key: str) -> float:
            val = data.get(key)
            if isinstance(val, (int, float)):
                return max(0.0, min(1.0, float(val)))
            raise KeyError(f"missing or invalid float: {key}")

        passes_raw = data.get("passes")
        passes: bool
        if isinstance(passes_raw, bool):
            passes = passes_raw
        elif isinstance(passes_raw, str):
            passes = passes_raw.lower() in {"true", "yes", "1"}
        else:
            raise KeyError("missing or invalid passes")

        reason = data.get("reason")
        if not isinstance(reason, str):
            reason = "llm judgment"

        return RelevanceScore(
            passes=passes,
            novelty=_get_float("novelty"),
            confidence=_get_float("confidence"),
            urgency=_get_float("urgency"),
            interruption_cost=_get_float("interruption_cost"),
            cooldown_ok=cooldown_ok,
            composite=_get_float("composite"),
            reasons=(reason,),
        )

    def _fallback_score(self, candidate: IdeaCandidate, cooldown_ok: bool) -> RelevanceScore:
        return RelevanceScore(
            passes=False,
            novelty=candidate.novelty,
            confidence=candidate.confidence,
            urgency=candidate.urgency,
            interruption_cost=candidate.interruption_cost,
            cooldown_ok=cooldown_ok,
            composite=0.0,
            reasons=("llm_fallback",),
        )

    def _cooldown_ok(self) -> bool:
        if not self._last_reflection_path.exists():
            return True
        last = self._read_last_timestamp()
        if last is None:
            return True
        now = datetime.now(UTC)
        if last.tzinfo is None:
            last = last.replace(tzinfo=UTC)
        elapsed = (now - last).total_seconds()
        return elapsed >= self._config.scheduler.cooldown_seconds

    def _read_last_timestamp(self) -> datetime | None:
        if not self._last_reflection_path.exists():
            return None
        try:
            raw: object = json.loads(self._last_reflection_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            return None
        if not isinstance(raw, dict):
            return None
        data = cast(dict[str, object], raw)
        ts_raw = data.get("timestamp")
        if not isinstance(ts_raw, str):
            return None
        try:
            return datetime.fromisoformat(ts_raw)
        except ValueError:
            return None


class IdeaCandidateGenerator:
    """Proactively generate new ideas from memory, sources, and conversations.

    The daemon calls this periodically. It reads whatever data exists and uses
    the LLM to produce genuinely new ideas — connections, contradictions,
    questions, and actions that the user hasn't explicitly asked about.
    """

    def __init__(
        self,
        project_root: Path | None = None,
        *,
        llm: ChatLLM | None = None,
        config: ReflectionSettings | None = None,
    ) -> None:
        from nuself.config import runtime_paths
        from nuself.llm import default_llm

        paths = runtime_paths(project_root)
        self._project_root = paths.project_root
        self._llm: ChatLLM = llm or default_llm(self._project_root)

        if config is not None:
            self._config_obj = config
        else:
            system_config = ConfigSystem.load(project_root=self._project_root)
            self._config_obj = system_config.reflection

        # Load language preference for user-facing output
        system_config = ConfigSystem.load(project_root=self._project_root)
        self._language_preference = system_config.chat.language_preference

    def generate(self, max_candidates: int = 3) -> list[IdeaCandidate]:
        from nuself.logs import write_log_event
        
        context = self._collect_context()
        if context.is_empty():
            write_log_event(
                "reflection",
                "candidate_generation_skipped",
                "no context available for idea generation",
                project_root=self._project_root,
                level="debug",
                status="skipped",
                metadata={"reason": "empty_context"}
            )
            return []
        try:
            candidates = self._generate_with_llm(context, max_candidates)
            if not candidates:
                write_log_event(
                    "reflection",
                    "cycle_no_candidates",
                    "reflection cycle generated no candidates",
                    project_root=self._project_root,
                    level="info",
                    status="completed",
                    metadata={"reason": "no_candidates"}
                )
            return candidates
        except (RuntimeError, ValueError, json.JSONDecodeError) as e:
            write_log_event(
                "reflection",
                "candidate_generation_failed",
                f"failed to generate candidates: {type(e).__name__}",
                project_root=self._project_root,
                level="warning",
                status="error",
                error=str(e)
            )
            return []

    def _collect_context(self) -> _ThinkingContext:
        threads = self._recent_thread_context()
        memories = self._recent_memory_context()
        profile = self._profile_context()
        sources = self._new_source_context()
        return _ThinkingContext(
            threads=threads,
            memories=memories,
            profile=profile,
            sources=sources,
        )

    def _generate_with_llm(self, context: _ThinkingContext, max_candidates: int) -> list[IdeaCandidate]:
        from nuself.llm import ChatMessage

        system_prompt = (
            "You are an independent thinker with access to someone's private memory, "
            "conversation history, reading notes, and personal profile.\n\n"
            "Your job: generate NEW ideas that the person hasn't explicitly asked about. "
            "Look for:\n"
            "- Contradictions between different memories or stated beliefs\n"
            "- Connections between seemingly unrelated topics\n"
            "- Unexplored questions suggested by the data\n"
            "- Actionable insights or recommendations\n"
            "- Patterns the person might not have noticed\n\n"
            "Do NOT summarize or rephrase existing content. "
            "Do NOT produce generic observations. "
            "Each idea must be genuinely novel — something the person would not have thought of on their own.\n\n"
            "Return a JSON object with a 'candidates' array (1 to 3 items). Each candidate:\n"
            '{\n'
            '  "title": "short title (max 80 chars)",\n'
            '  "body": "2-4 sentences describing the new idea",\n'
            '  "candidate_type": "question|connection|contradiction|action|profile_update",\n'
            '  "confidence": 0.0-1.0,\n'
            '  "novelty": 0.0-1.0,\n'
            '  "urgency": 0.0-1.0,\n'
            '  "interruption_cost": 0.0-1.0\n'
            '}\n\n'
            "Return ONLY the JSON object. No markdown fences."
        )
        if self._language_preference != "en":
            system_prompt += f"\n\nRespond in {self._language_preference}."

        user_message = context.to_prompt()
        messages = [
            ChatMessage(role="system", content=system_prompt),
            ChatMessage(role="user", content=user_message),
        ]
        raw = self._llm.complete(messages)
        return self._parse_candidates(raw, max_candidates)

    def _parse_candidates(self, raw: str, max_candidates: int) -> list[IdeaCandidate]:
        stripped = raw.strip()
        if stripped.startswith("```"):
            lines = [line for line in stripped.splitlines() if not line.strip().startswith("```")]
            stripped = "\n".join(lines).strip()

        try:
            output = CandidateListOutput.model_validate_json(stripped)
            valid_types = {"question", "connection", "contradiction", "action", "profile_update", "share_bundle"}
            now = datetime.now(UTC)
            prefix = now.strftime("%Y%m%d-%H%M%S")
            results: list[IdeaCandidate] = []
            for item in output.candidates[:max_candidates]:
                ctype = item.candidate_type if item.candidate_type in valid_types else "question"
                results.append(IdeaCandidate(
                    id=f"candidate-{prefix}-{now.microsecond:06d}",
                    title=item.title[:80],
                    body=item.body,
                    candidate_type=cast(IdeaCandidateType, ctype),
                    confidence=max(0.0, min(1.0, item.confidence)),
                    novelty=max(0.0, min(1.0, item.novelty)),
                    urgency=max(0.0, min(1.0, item.urgency)),
                    interruption_cost=max(0.0, min(1.0, item.interruption_cost)),
                    evidence_refs=(),
                    suggested_thread_id=None,
                    source_summary="llm-generated",
                    created_at=now_iso(),
                ))
            return results
        except (ValidationError, json.JSONDecodeError):
            pass

        parsed: object = json.loads(stripped)
        if not isinstance(parsed, dict):
            raise ValueError("LLM response is not a JSON object")
        data = cast(dict[str, object], parsed)
        raw_candidates = data.get("candidates")
        if not isinstance(raw_candidates, list):
            raise ValueError("LLM response missing 'candidates' array")
        candidates_list = cast(list[object], raw_candidates)

        valid_types = {"question", "connection", "contradiction", "action", "profile_update", "share_bundle"}
        results: list[IdeaCandidate] = []
        for item in candidates_list[:max_candidates]:
            if not isinstance(item, dict):
                continue
            c = cast(dict[str, object], item)
            title = c.get("title")
            body = c.get("body")
            if not isinstance(title, str) or not isinstance(body, str):
                continue
            candidate_type = c.get("candidate_type", "question")
            if not isinstance(candidate_type, str) or candidate_type not in valid_types:
                candidate_type = "question"
            results.append(IdeaCandidate(
                id=f"candidate-{datetime.now(UTC).strftime('%Y%m%d-%H%M%S')}-{datetime.now(UTC).microsecond:06d}",
                title=title[:80],
                body=body,
                candidate_type=cast(IdeaCandidateType, candidate_type),
                confidence=_clamp_float(c.get("confidence"), 0.5),
                novelty=_clamp_float(c.get("novelty"), 0.5),
                urgency=_clamp_float(c.get("urgency"), 0.3),
                interruption_cost=_clamp_float(c.get("interruption_cost"), 0.2),
                evidence_refs=(),
                suggested_thread_id=None,
                source_summary="llm-generated",
                created_at=now_iso(),
            ))
        return results

    def _recent_thread_context(self, max_threads: int = 5, max_messages: int = 10) -> str:
        from nuself.agent.chat import ThreadStore

        store = ThreadStore(self._project_root)
        lines: list[str] = []
        for thread_id in reversed(store.list()[-max_threads:]):
            state = store.load(thread_id)
            lines.append(f"Thread {thread_id}:")
            for msg in state.messages[-max_messages:]:
                lines.append(f"  {msg.role}: {msg.content[:120]}")
        return "\n".join(lines)

    def _recent_memory_context(self, max_entries: int = 8) -> str:
        from nuself.memory.repository import MemoryEntryRepository

        repo = MemoryEntryRepository(self._project_root)
        lines: list[str] = []
        for entry in repo.list()[-max_entries:]:
            lines.append(f"- [{entry.type}] {entry.title}: {entry.body[:120]}")
        return "\n".join(lines)

    def _profile_context(self, max_items: int = 10) -> str:
        from nuself.profile.repository import ProfileItemRepository

        repo = ProfileItemRepository(self._project_root)
        lines: list[str] = []
        for item in repo.list()[:max_items]:
            tags = f" (tags: {', '.join(item.tags)})" if item.tags else ""
            lines.append(f"- [{item.type}] {item.title}{tags}: {item.body[:120]}")
        return "\n".join(lines)

    def _new_source_context(self, max_sources: int = 5) -> str:
        from nuself.memory.source_repository import SourceRepository

        repo = SourceRepository(self._project_root)
        lines: list[str] = []
        for doc in repo.list_documents()[-max_sources:]:
            lines.append(f"- {doc.title or doc.id}")
        return "\n".join(lines)


@dataclass(frozen=True)
class _ThinkingContext:
    """All available material for proactive idea generation."""

    threads: str
    memories: str
    profile: str
    sources: str

    def is_empty(self) -> bool:
        return not (self.threads or self.memories or self.profile or self.sources)

    def to_prompt(self) -> str:
        sections: list[str] = []
        if self.memories:
            sections.append(f"## Memory entries\n{self.memories}")
        if self.threads:
            sections.append(f"## Recent conversations\n{self.threads}")
        if self.profile:
            sections.append(f"## Personal profile\n{self.profile}")
        if self.sources:
            sections.append(f"## Source documents\n{self.sources}")
        return "\n\n".join(sections)


def _clamp_float(value: object, default: float) -> float:
    if isinstance(value, (int, float)):
        return max(0.0, min(1.0, float(value)))
    return default
